config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shoes
  namespace :admin do
    resources :shoes
    root to:'shoes#home'
  end
  root to: 'shoes#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :shoe
end

app/models/shoe.rb
class Shoe < ApplicationRecord
    has_many :shoe_sizes, dependent: :destroy
    has_many :colors, dependent: :destroy
    validates :name, :description, :price, presence:true
    validates :name, :price, uniqueness: true

    has_one_attached :picture_3D
end

app/models/shoe_size.rb
class ShoeSize < ApplicationRecord
  belongs_to :shoe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/shoes_controller.rb
class Admin::ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy,]
  before_action :authenticate_user!
  before_action :require_admin

  def home
    @shoes = Shoe.all
  end

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = Shoe.find(params[:id])
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :show, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    @shoe = Shoe.new(shoe_params)
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = Shoe.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :price, :description, :picture_3D, :color)
    end

    def require_admin
      unless current_user.admin?
        redirect_to admin_shoes_path
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  def home
    @shoes = Shoe.all
  end

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = Shoe.find(params[:id])
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render :index, status: :created, location: @shoe }
      else
        format.html { render :new }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    @shoe = Shoe.new(shoe_params)
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoe }
      else
        format.html { render :edit }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = Shoe.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :price, :description, :picture_3D, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shoes/_form.html.erb
<%= form_with(model: shoe, local: true) do |form| %>
  <% if shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

   <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>


  <div class="field">
    <%= form.label :picture_3D %>
    <%= form.file_field :picture_3D %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/shoes/edit.html.erb
<div class="container container-form">
     <h1>Editing Shoe</h1>

    <div class="form-new">
        <%= render 'form', shoe: @shoe %>
    </div>
    <%= link_to 'Show', @shoe %> |
    <%= link_to 'Back', admin_shoes_path %>
</div>

app/views/admin/shoes/home.html.erb
<section id="home">
<header class="container-fluid">
    <%# <a class="navbar-brand" href="index.html"><img src="images/nike-logo.png" alt=""></a> %>
     <%= link_to admin_root_path, class: "navbar-brand" do %>
    <%= image_tag "nike-logo.png", height: 50 %>
    <% end %>
    <!-- <div class="btn-close"></div> -->
    <div class="connexion-container">
      <% if current_user && current_user.admin? %>
          <% if user_signed_in? %>
          <%= link_to t(".sign_out", default: "Déconnecter"), destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to t(".sign_in", default: "Se Connecter"), new_user_session_path,class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      <%end%>
    </div>
  </header>

  <div class="container-content">

    <div class="hold">
      HOLD IT
    </div>

    <div class="container-colors">
      <div class="colors-btn white"></div>
      <div class="colors-btn green"></div>
      <div class="colors-btn purple"></div>
      <div class="colors-btn red"></div>
    </div>
    <%= link_to  admin_shoes_path(@shoe) do %>
      <div class="btn-container">
          <div class="cross-btn"></div>
      </div>
    <% end %>
  </div>

  <section id="canvas-scene">
  </section>

  <!-- <div class="btn-hold-container">
    <div class="btn-hold">
      <div class="hover"></div>
    </div>
    <div class="label-btn">
      Press & hold
    </div>
  </div> -->


  <!-- <section class="loader">
    <div class="image-container">
      <img src="images/NikeAirMax95White.png" alt="">
    </div>
    <div class="row">
      <div class="d-none d-lg-block col-5"></div>
      <div id="container-brand" class="col-12 col-lg-7 container-brand">
        <div class="line">
          <span class="brand">NIKE 3D </span>
        </div>
      </div>
    </div>
  </section> -->





  <div class="fake-cursor"></div>
  </section>
  <script>
  var scene;
var camera;
var renderer;
var width;
var height;
var canvas = document.getElementById("canvas-scene");

function init() {

  width = $("#canvas-scene").width();
  height = $("#canvas-scene").height();

  scene = new THREE.Scene();

  renderer = new THREE.WebGLRenderer();
  renderer.setSize(width, height);
  renderer.setPixelRatio(window.devicePixelRatio);
  canvas.appendChild(renderer.domElement);

  camera = new THREE.PerspectiveCamera(50, width/height, 0.1, 1000);
  camera.position.set(0,-.5,38);
  camera.lookAt(0,0,0);

  scene.add(camera);

  var light1 = new THREE.PointLight(0xffffff, 1);
  light1.position.set(-100, -250, 100);
  scene.add(light1);

  var keyLight = new THREE.DirectionalLight(new THREE.Color(0xffffff), 1);
  keyLight.position.set(-100, 0, 100);
  var fillLight = new THREE.DirectionalLight(new THREE.Color(0xffffff), 1);
  fillLight.position.set(100, 0, 100);
  var backLight = new THREE.DirectionalLight(0xffffff, 1);
  backLight.position.set(100, 0, -100);

  scene.add(keyLight);
  scene.add(fillLight);
  scene.add(backLight);

  controls = new THREE.OrbitControls(camera, renderer.domElement);
  controls.enablePan = false;
  controls.zoomSpeed = .7;


  myLoader();

  window.addEventListener('resize', function() {
    width = $("#canvas-scene").width();
    height = $("#canvas-scene").height();
    renderer.setSize(width, height);
    camera.aspect = width / height;
    camera.updateProjectionMatrix();
  });

}

function myLoader() {

  var rotationSpeed;
  var loader = new THREE.GLTFLoader()
  var path = '<%= Shoe.all.count > 0 ? url_for(Shoe.last.picture_3D) : "" %>'

  loader.load(path, function(gltf) {
    var mesh = gltf.scene;

    mesh.rotation.y = -3.2;

    rotationSpeed = .01;
    rotation();
    function rotation() {
      mesh.rotation.y -= rotationSpeed;
      renderer.render(scene, camera);
      controls.update();
      requestAnimationFrame(rotation);
    };

    mesh.traverse(function(node){
       if (node.isMesh) {
         node.material.color = new THREE.Color(0xffffff);
         node.material.wireframe = false;
       }
    });

    var Handler = function() {
       this.clickHandler = function() {
          var self = this;
          this.timerId = setTimeout(function() {
              // ACCELERATION
              rotationSpeed = 0.2;

              mesh.traverse(function(node){
                 if (node.isMesh) {
                   node.material.color = new THREE.Color(0xffffff);
                   node.material.wireframe = true;
                 }
              });

              let hold = new TimelineMax();


              TweenMax.to(".hold", .01, {autoAlpha: 1})



          },1);

          this.timerId = setTimeout(function() {
            rotationSpeed = .01;
            mesh.traverse(function(node){
               if (node.isMesh) {
                 node.material.wireframe = false;
                 node.material.color = new THREE.Color(newColor);
               }
            });
            TweenMax.to(".hold", .01, {autoAlpha: 0})
          },500);
       };

       this.cancelHandler = function() {
           if (this.timerId) {
              clearTimeout(this.timerId);
              rotationSpeed = 0.01;
              mesh.rotation.x = 0;
              mesh.rotation.z = 0;
              mesh.traverse(function(node){
                 if (node.isMesh) {
                   node.material.wireframe = false;
                 }
              });
           }
           TweenMax.to(".hold", .01, {autoAlpha: 0})
       }
    }


    var h = new Handler();
    var newColor;
    $(".colors-btn").mousedown(h.clickHandler.bind(h));
    $(".colors-btn").mousedown(function() {
      newColor = "" + $(this).css("background-color") + "";
      console.log(newColor);
    });
    $(".colors-btn").mouseup(h.cancelHandler.bind(h));
    // document.getElementsByClassName("colors-btn").addEventListener('mousedown', h.clickHandler.bind(h));
    // document.getElementsByClassName("colors-btn").addEventListener('mouseup', h.cancelHandler.bind(h));

    scene.add(mesh);
  });

}

function animate() {
  width = $("#canvas-scene").width();//pas sur
  height = $("#canvas-scene").height();//pas sur
  renderer.setSize(width, height);//pas sur
  camera.aspect = width / height;//pas sur

  camera.updateProjectionMatrix();
  requestAnimationFrame(animate);
  renderer.render(scene, camera);
  controls.update();
};

window.addEventListener('DOMContentLoaded', function () {
    init();
    animate();
});








//

  </script>
  <script>$(".cross-btn, .colors-btn").mouseover(function() { console.log("Hello");
  TweenMax.to(".fake-cursor", .5, {autoAlpha: .5, backgroundColor: $(this).css("background-color"), width: 70, height: 70, x: "-50%", y: "-50%", ease: Power3.easeOut});
});

$(".cross-btn, .colors-btn").mouseleave(function() {
  TweenMax.to(".fake-cursor", .5, {autoAlpha: .3, width: 13, height: 13, x: "0", y: "0", ease: Power3.easeOut});
});
</script>

app/views/admin/shoes/index.html.erb
<section id="shop">

<header class="container-fluid">


    <%= link_to admin_root_path, class: "navbar-brand" do %>

    <%= image_tag "nike-logo.png", height: 50 %>
    <% end %>
     <!-- Login link (when logged out) -->
    <div class="connexion-container">
      <% if current_user && current_user.admin? %>
          <% if user_signed_in? %>
          <%= link_to t(".sign_out", default: "Déconnecter"), destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to t(".sign_in", default: "Se Connecter"), new_user_session_path,class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      <%end%>
    </div>
  </header>

  <div class="container-content container-fluid">
    <div class="row">
      <% @shoes.each do |shoe| %>
      <div class="col-5">
        <div class="container-description">
          <h1 class="name-product"><%= shoe.name %></h1>
          <h2 class="color-product"><%= shoe.color %></h2>
          <h3 class="price-product"><%= shoe.price %> $</h3>
          <p class="desc-product">
            <%= shoe.description %>
          </p>
          <div class="size-product">
            <input class="size available" type="button" id="size" value="38">
            <input class="size available" type="button" id="size" value="39">
            <input class="size available" type="button" id="size" value="40">
            <input class="size not-available" type="button" id="size" value="41">
            <input class="size not-available" type="button" id="size" value="42">
            <input class="size available" type="button" id="size" value="44">
            <input class="size available" type="button" id="size" value="45">
            <input class="size available" type="button" id="size" value="46">
          </div>

          <div class="container-submit">
            <input type="button" id="submit" value="Commander">
          </div>

          <% end %>
        <%= link_to 'New Shoe', new_admin_shoe_path %>
        </div>
      </div>

      <div id="canvas-scene" class="col-7">
        <!-- THREE JS SCENE HERE -->
      </div>
      <%# <%= link_to 'Edit', edit_admin_shoe_path(@shoe) %>

<%# <%= link_to 'Destroy', @shoe, method: :delete, class: "submit", data: { confirm: 'Are you sure?' }  %>
  </div>

</section>

<script>
    var scene;
    var camera;
    var renderer;
    var width;
    var height;
    var canvas = document.getElementById("canvas-scene");

    function init() {

      width = $("#canvas-scene").width();
      height = $("#canvas-scene").height();

      scene = new THREE.Scene();

      renderer = new THREE.WebGLRenderer();
      renderer.setSize(width, height);
      renderer.setPixelRatio(window.devicePixelRatio);
      canvas.appendChild(renderer.domElement);

      camera = new THREE.PerspectiveCamera(50, width/height, 0.1, 1000);
      camera.position.set(0,-.5,27.5);
      camera.lookAt(0,0,0);

      scene.add(camera);

      // renderer.setClearColor(0x333F47);

      var light1 = new THREE.PointLight(0xffffff, 1);
      light1.position.set(-100, -250, 100);
      scene.add(light1);

      var keyLight = new THREE.DirectionalLight(new THREE.Color(0xffffff), 0.5);
      keyLight.position.set(-100, 0, 100);
      var fillLight = new THREE.DirectionalLight(new THREE.Color(0xffffff), 0.75);
      fillLight.position.set(100, 0, 100);
      var backLight = new THREE.DirectionalLight(0xffffff, 1);
      backLight.position.set(100, 0, -100).normalize();

      scene.add(keyLight);
      scene.add(fillLight);
      scene.add(backLight);

      controls = new THREE.OrbitControls(camera, renderer.domElement);

      myLoader();

      window.addEventListener('resize', function() {
        width = $("#canvas-scene").width();
        height = $("#canvas-scene").height();
        renderer.setSize(width, height);
        camera.aspect = width / height;
        camera.updateProjectionMatrix();
      });

    }

    function myLoader() {

      var rotationSpeed;
      var loader = new THREE.GLTFLoader()
      var path = '<%= Shoe.all.count > 0 ? url_for(Shoe.last.picture_3D) : "" %>'

      loader.load(path, function(gltf) {
        var mesh = gltf.scene;

        mesh.rotation.y = -3.2;

        rotationSpeed = .02;
        rotation();
        function rotation() {
          mesh.rotation.y -= rotationSpeed;
          renderer.render(scene, camera);
          controls.update();
          requestAnimationFrame(rotation);
        };

        mesh.traverse(function(node){
          if (node.isMesh) {
            node.material.color = new THREE.Color(0xffffff);
          }
        });

        var Handler = function() {
          this.clickHandler = function() {
              var self = this;
              this.timerId = setTimeout(function() {
                  // ACCELERATION
                  rotationSpeed = 0;
              },1);

              this.timerId = setTimeout(function() {
                  rotationSpeed = 0;
              },1000);
          };

          this.cancelHandler = function() {
              if (this.timerId) {
                  clearTimeout(this.timerId);
                  rotationSpeed = 0;
                  mesh.rotation.x = 0;
                  mesh.rotation.z = 0;
              }
          }
        }
        var h = new Handler();
        addEventListener('mousedown', h.clickHandler.bind(h));
        addEventListener('mouseup', h.cancelHandler.bind(h));

        scene.add(mesh);
      });

    }

    function animate() {
      requestAnimationFrame(animate);
      renderer.render(scene, camera);
      controls.update();
    };

    window.addEventListener('DOMContentLoaded', function () {
        init();
        animate();
    });








    //
</script>

app/views/admin/shoes/new.html.erb
<div class="container container-form">
     <h1>New Shoe</h1>

    <div class="form-new">
        <%= render 'form', shoe: @shoe %>
    </div>

    <%= link_to 'Back', admin_shoes_path %>
</div>

app/views/admin/shoes/show.html.erb
<header class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "nike-logo.png", height: 50 %>
    <% end %>
    <%# <div class="btn-close"></div> %>
     <!-- Login link (when logged out) -->
    <% if current_user && current_user.admin? %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%end%>
</header>

  <div class="container-content container-fluid">
    <div class="row">
      <div class="col-5">
        <div class="container-description">
          <h1 class="name-product"><%= @shoe.name %></h1>
          <h2 class="color-product"><%= shoe.color %></h2>
          <h3 class="price-product"><%= @shoe.price %></h3>
          <p class="desc-product">
            <%= @shoe.description%>
          </p>
          <div class="size-product">
            <input class="size available" type="nomber" id="size" value="38">
            <input class="size available" type="nomber" id="size" value="39">
            <input class="size available" type="nomber" id="size" value="40">
            <input class="size not-available" type="nomber" id="size" value="41">
            <input class="size not-available" type="nomber" id="size" value="42">
            <input class="size available" type="nomber" id="size" value="44">
            <input class="size available" type="nomber" id="size" value="45">
            <input class="size available" type="nomber" id="size" value="46">
            <input class="size available" type="nomber" id="size" value="47">
          </div>
          <%= link_to 'Edit', edit_admin_shoe_path(@shoe) %>
          <%= link_to 'New Shoe', new_admin_shoe_path %>
          <%= link_to 'Destroy', @shoe, method: :delete, class: "submit", data: { confirm: 'Are you sure?' }  %>
          <%= link_to 'Commander', @shoe, id:"submit" %>
          <%# <input type="text" id="submit" value="Commander"> %>

      </div>
    </div>
    <div id="canvas-scene" class="col-7">
        <!-- THREE JS SCENE HERE -->
    </div>

  </div>


</div>



<%= link_to 'Back', admin_shoes_path %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shoes/index.html.erb
<section id="shop">

<header class="container-fluid">

    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "nike-logo.png", height: 50 %>
    <% end %>
    <%# <div class="btn-close"></div> %>
     <!-- Login link (when logged out) -->
    <div class="connexion-container">
      <% if current_user && current_user.admin? %>
          <% if user_signed_in? %>
          <%= link_to t(".sign_out", default: "Déconnecter"), destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to t(".sign_in", default: "Se Connecter"), new_user_session_path,class: "navbar-wagon-item navbar-wagon-link" %>
        <% end %>
      <%end%>
    </div>
  </header>

  <div class="container-content container-fluid">
    <div class="row">
      <% @shoes.each do |shoe| %>
      <div class="col-5">
        <div class="container-description">
          <h1 class="name-product"><%= shoe.name %></h1>
          <h2 class="color-product"><%= shoe.color %></h2>
          <h3 class="price-product"><%= shoe.price %> $</h3>
          <p class="desc-product">
            <%= shoe.description %>
          </p>
          <div class="size-product">
            <input class="size available" type="button" id="size" value="38">
            <input class="size available" type="button" id="size" value="39">
            <input class="size available" type="button" id="size" value="40">
            <input class="size not-available" type="button" id="size" value="41">
            <input class="size not-available" type="button" id="size" value="42">
            <input class="size available" type="button" id="size" value="44">
            <input class="size available" type="button" id="size" value="45">
            <input class="size available" type="button" id="size" value="46">
          </div>

          <div class="container-submit">
            <input type="button" id="submit" value="Commander">
          </div>


          <% end %>

        </div>
      </div>

      <div id="canvas-scene" class="col-7">
        <!-- THREE JS SCENE HERE -->
      </div>

  </div>
  <%= link_to 'Edit', edit_admin_shoe_path(@shoes) %>
 <%= link_to 'New Shoe', new_admin_shoe_path %>
<%= link_to 'Destroy', @shoe, method: :delete, class: "submit", data: { confirm: 'Are you sure?' }  %>
</section>

<script>
    var scene;
    var camera;
    var renderer;
    var width;
    var height;
    var canvas = document.getElementById("canvas-scene");

    function init() {

      width = $("#canvas-scene").width();
      height = $("#canvas-scene").height();

      scene = new THREE.Scene();

      renderer = new THREE.WebGLRenderer();
      renderer.setSize(width, height);
      renderer.setPixelRatio(window.devicePixelRatio);
      canvas.appendChild(renderer.domElement);

      camera = new THREE.PerspectiveCamera(50, width/height, 0.1, 1000);
      camera.position.set(0,-.5,27.5);
      camera.lookAt(0,0,0);

      scene.add(camera);

      // renderer.setClearColor(0x333F47);

      var light1 = new THREE.PointLight(0xffffff, 1);
      light1.position.set(-100, -250, 100);
      scene.add(light1);

      var keyLight = new THREE.DirectionalLight(new THREE.Color(0xffffff), 0.5);
      keyLight.position.set(-100, 0, 100);
      var fillLight = new THREE.DirectionalLight(new THREE.Color(0xffffff), 0.75);
      fillLight.position.set(100, 0, 100);
      var backLight = new THREE.DirectionalLight(0xffffff, 1);
      backLight.position.set(100, 0, -100).normalize();

      scene.add(keyLight);
      scene.add(fillLight);
      scene.add(backLight);

      controls = new THREE.OrbitControls(camera, renderer.domElement);

      myLoader();

      window.addEventListener('resize', function() {
        width = $("#canvas-scene").width();
        height = $("#canvas-scene").height();
        renderer.setSize(width, height);
        camera.aspect = width / height;
        camera.updateProjectionMatrix();
      });

    }

    function myLoader() {

      var rotationSpeed;
      var loader = new THREE.GLTFLoader()
      var path = '<%= Shoe.all.count > 0 ? url_for(Shoe.last.picture_3D) : "" %>'

      loader.load(path, function(gltf) {
        var mesh = gltf.scene;

        mesh.rotation.y = -3.2;

        rotationSpeed = .02;
        rotation();
        function rotation() {
          mesh.rotation.y -= rotationSpeed;
          renderer.render(scene, camera);
          controls.update();
          requestAnimationFrame(rotation);
        };

        mesh.traverse(function(node){
          if (node.isMesh) {
            node.material.color = new THREE.Color(0xffffff);
          }
        });

        var Handler = function() {
          this.clickHandler = function() {
              var self = this;
              this.timerId = setTimeout(function() {
                  // ACCELERATION
                  rotationSpeed = 0;
              },1);

              this.timerId = setTimeout(function() {
                  rotationSpeed = 0;
              },1000);
          };

          this.cancelHandler = function() {
              if (this.timerId) {
                  clearTimeout(this.timerId);
                  rotationSpeed = 0;
                  mesh.rotation.x = 0;
                  mesh.rotation.z = 0;
              }
          }
        }
        var h = new Handler();
        addEventListener('mousedown', h.clickHandler.bind(h));
        addEventListener('mouseup', h.cancelHandler.bind(h));

        scene.add(mesh);
      });

    }

    function animate() {
      requestAnimationFrame(animate);
      renderer.render(scene, camera);
      controls.update();
    };

    window.addEventListener('DOMContentLoaded', function () {
        init();
        animate();
    });








    //
</script>

app/views/shoes/new.html.erb
<div class="container container-form">
     <h1>New Shoe</h1>

    <div class="form-new">
        <%= render 'form', shoe: @shoe %>
    </div>

    <%= link_to 'Back', admin_shoes_path %>
</div>